model_name_or_path: Qwen/Qwen2.5-VL-7B-Instruct
adapter_name_or_path: saves/qwen2.5_vl-7b/lora/sft/grocery_589824_res_simple
template: qwen2_vl
finetuning_type: lora
infer_backend: huggingface  # choices: [huggingface, vllm]
image_max_pixels: 589824