### model
model_name_or_path: llava-hf/llava-1.5-7b-hf

### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: all

### dataset
dataset: zeki_grocery_train, freiburg_grocery, fruits_and_vegs_grocery
template: llava
cutoff_len: 8192
overwrite_cache: true
preprocessing_num_workers: 16
image_max_pixels: 589824 # = width * height < value
packing: true

### output
output_dir: saves/llava-1.5-7b-hf/lora/sft/grocery_589824_res
logging_steps: 40
save_steps: 40
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 2
gradient_accumulation_steps: 8
learning_rate: 1.0e-4
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
val_size: 0.1
per_device_eval_batch_size: 2
eval_strategy: steps

### monitoring
report_to: wandb
run_name: llava_1.5_lora_sft_589824_res
