### model
model_name_or_path: Qwen/Qwen2.5-VL-7B-Instruct

### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: all

### dataset
dataset: zeki_grocery_train, freiburg_grocery, fruits_and_vegs_grocery
template: qwen2_vl
cutoff_len: 8192
overwrite_cache: true
preprocessing_num_workers: 16
image_max_pixels: 700000 # = width * height < value
packing: true

### output
output_dir: saves/qwen2.5_vl-7b/lora/sft/grocery_700000_res
logging_steps: 40
save_steps: 40
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 1.0e-4
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
val_size: 0.1
per_device_eval_batch_size: 1
eval_strategy: steps

### monitoring
report_to: wandb
run_name: qwen2.5vl_7b_lora_sft_700000_res
