model_name_or_path: mistral-community/pixtral-12b
adapter_name_or_path: saves/pixtral/lora/sft/grocery_589824_res
template: pixtral
finetuning_type: lora
infer_backend: huggingface  # choices: [huggingface, vllm]
image_max_pixels: 589824